version: '3'
services:
  web:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./public_html:/public_html
      - ./conf.d:/etc/nginx/conf.d
      - /etc/hostname:/run/hostname_server
    restart: always
    networks:
      - nginxphp
  php:
    image: php:7.1.11-fpm-alpine
    volumes:
      - ./public_html:/public_html
      - /etc/hostname:/run/hostname_server
    restart: always
    expose:
      - 9000
    networks:
      - nginxphp
networks:
  nginxphp:
