---
 - name: Desabilitando o firewall
   ansible.builtin.systemd:
     name: firewalld
     state: stopped
     enabled: no
 - name: Adicionando o repositorio Oficial Docker
   get_url:
     url: https://download.docker.com/linux/centos/docker-ce.repo
     dest: /etc/yum.repos.d/docker-ce.repo
     mode: '0440'
 - name: Instalando pacotes do Docker
   yum:
     name: "{{pacotes}}"
     state: latest
   vars:
     pacotes:
       - docker-ce
       - docker-ce-cli
       - containerd.io
       - python3-pip 
 - name: Iniciando o servico do Docker
   ansible.builtin.systemd:
     name: docker
     state: started
     enabled: yes
 - name: Criando o docker-compose - x86_64
   get_url:
     url: https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-linux-x86_64
     dest: /usr/local/bin/docker-compose
     mode: 0551
   when: ansible_architecture == "x86_64"
 - name: Criando o docker-compose - aarch64
   get_url:
     url: https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-linux-aarch64
     dest: /usr/local/bin/docker-compose
     mode: 0551
   when: ansible_architecture == "aarch64"
 - name: Install PIP depencie
   pip:
     name:
       - docker
 - name: Create nginx container
   ansible.builtin.shell: docker-compose -f ./docker-compose/docker-compose.yml up -d
     
